### ISSUE TITLE
Errors in two ESGF notebooks

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/cmip6-cookbook#78]
The nightly build has been failing because `esgf2-arm-comparison.ipynb` and `enso-esgf.ipynb` are running into some errors. Both errors ([comparison](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/7648312399/job/20840871420#step:17:175) and [enso](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/7648312399/job/20840871420#step:17:447)) seem related to data access.

**Comment by r-ford** [comment]
@mgrover1 Do you know if something changed over the last couple months that would be causing these errors?

**Comment by mgrover1** [comment]
@r-ford - I am looking into this, it appears there is an issue with the binder

```
2024-02-12 00:54:54 [info     ] Binder: Build Failed Failed to create temporary user for ktyle/binder-dev-projectpythia-2dcmip6-2dcookbook-81d820:5c2f006b6e304dd962e20a4c5907ee18378906ab
```

Any idea what could be causing this @ktyle ?

**Comment by ktyle** [comment]
@mgrover1 JS2 had some maintenance issues this morning ... they look to have been resolved as of 1:25 PM EST. Can you try again?

**Comment by mgrover1** [comment]
You bet 👍

**Comment by mgrover1** [comment]
I am still seeing

Binder: Build Failed Failed to create temporary user for ktyle/binder-dev-projectpythia-2dcmip6-2dcookbook-81d820:5c2f006b6e304dd962e20a4c5907ee18378906ab

**Comment by ktyle** [comment]
okee dokee I'll take a look!

**Comment by ktyle** [comment]
I'm going to open a ticket with JS2 support on this; see zonca/jupyterhub-deploy-kubernetes-jetstream#74

**Comment by ktyle** [comment]
Our binderhub should be working again ...

**Comment by r-ford** [comment]
It looks like the notebooks are still failing with the same errors.

**Comment by mgrover1** [comment]
Looks like the build is failing due to updates in intake-esgf - I can tackle this this week @r-ford
